### PR TITLE
Activating Open Collective

### PR DESCRIPTION
**Pull request by monkeywithacupcake**
Hi, I'm making updates for Open Collective. Either you or a supporter signed this repo up for Open Collective. This pull request adds backers and sponsors from your Open Collective https://opencollective.com/eclipse-plugins ❤️
  
  It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [[more info](https://github.com/opencollective/opencollective/wiki/Github-banner)]. See how it looks on [this repo](https://github.com/apex/apex#backers).
You can also add a "Donate" button to your website and automatically show your backers and sponsors there with our widgets. Have a look here: https://opencollective.com/widgets

  P.S: As with any pull request, feel free to comment or suggest changes. The only thing "required" are the placeholders on the README because we believe it's important to acknowledge the people in your community that are contributing (financially or with code!).

  Thank you for your great contribution to the open source community. You are awesome! 🙌
  And welcome to the open collective community! 😊

  Come chat with us in the #opensource channel on https://slack.opencollective.com - great place to ask questions and share best practices with other open source sustainers!

### CODE REVIEW

**Comment by ilg-ul** [comment]
unfortunately automatically submitting pull request does not work as expected, the master branch is updated from the develop branch after each release, and now it is half way between releases.

I'll try to manually apply the changes to README in the next release.

**Comment by ilg-ul** [comment]
And, @monkeywithacupcake, if you allow me one suggestion: when you create the open collective url, for projects part of an organisation, please also use the organisation name; for example in my case it should have been `gnu-mcu-eclipse/eclipse-plugins`, not simply `eclipse-plugins`, since the short name does not say much about the project.

Actually this was one of the reasons I was a bit dissapointed about and delayed linking to open collective.

Can you manually fix my url?

**Comment by monkeywithacupcake** [comment]
All of the collectives that I have seen just use one collective. Some use their organization and others use the repo. I am not sure if it is possible to use both. I'll ask some other folks.

**Comment by ilg-ul** [comment]
@monkeywithacupcake, I managed to change the url to `gnu-mcu-eclipse`, which is more appropriate.

I'll try to link to it from all GitHub projects in the GNU MCU Eclipse organization.

**Comment by ilg-ul** [comment]
URLs updated and manually applied: https://github.com/gnu-mcu-eclipse/eclipse-plugins/commit/77620a83531c2441e3442016a87efc96f163530e

**Pull request closed without merging**
